services:
  backend:
    build:
      context: ./apartments_service
      dockerfile: ../Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./apartments_service/media/:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: realestate
      POSTGRES_USER: realuser
      POSTGRES_PASSWORD: realpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apartments_service/media/:/app/media/
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data: 