services:
  backend:
    build:
      context: ./apartments_service
      dockerfile: Dockerfile.backend
    command: gunicorn apartments_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: realestate
      POSTGRES_USER: realuser
      POSTGRES_PASSWORD: realpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    stdin_open: true
    tty: true
    ports:
      - "80:80"
    depends_on:
      - backend

  nginx:
    build: ./apartments_service/nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 81:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: